### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by 17365249005** [zhaohaojie1998/DRL-for-Path-Planning#2]
缺少demo_dynamic.pth文件

**Comment by zhaohaojie1998** [comment]
还没更完呢，随缘更新

**Comment by 17365249005** [comment]
大佬可以发下pth文件吗，我想跑一下试试，目前报了很多错，还在更改中...



在 2024-03-19 16:58:56，"zhaohaojie1998" ***@***.***> 写道：

还没更完呢，随缘更新
