### ISSUE TITLE
你好 作者，我在运行demo_train与动态训练均出现一些问题，请问这个该如何解决？

### ISSUE THREAD

**Issue by guest-oo** [zhaohaojie1998/DRL-for-Path-Planning#3]
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if deterministic: u = mu

TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if with_logprob:

mix——obs中log = SummaryWriter(log_dir = "./tensorboard_log")  语句出现 tensorflow.python.framework.errors_impl.FailedPreconditionError: . is not a directory的报错

**Comment by zhaohaojie1998** [comment]
第一个是警告，不是错误
第二个：不要用 Tensorboard 就完了

**Comment by zhaohaojie1998** [comment]
1.训练用pytorch啊，onnx模型只是算法的输出，用于将训练好的策略在其他平台或者编程语言上使用。那几个参数是控制导出的策略的计算结构，不影响求解最优动作。
2.可以自己写个Logger

**Comment by guest-oo** [comment]
请问 作者可以给一下代码的参考的文献吗？

**Comment by zhaohaojie1998** [comment]
文献是SAC算法+Pytorch源码+Gym源码

**Comment by guest-oo** [comment]
请问作者 如果我想限制静态避障的运动方向与运动步长 我该在哪个代码进行如何修改？
