### ISSUE TITLE
运行env.render（）时，第二次及以后的axex进行set_data和set_offsets重绘图异常

### ISSUE THREAD

**Issue by Horseant** [zhaohaojie1998/DRL-for-Path-Planning#4]
![1712577311550](https://github.com/zhaohaojie1998/DRL-for-Path-Planning/assets/50021046/fdcadf4a-11a9-4633-8f6a-48e9a75a701c)
大佬你好！执行代码中自带的测试函数，发现只有第一次调用env.render()被执行，第二次及以后执行的这一部分绘图的代码并未触发
![image](https://github.com/zhaohaojie1998/DRL-for-Path-Planning/assets/50021046/e819244d-a769-47b0-8e0a-d340ebc8caed)
想请教一下是什么原因，打印发现self.log在每次执行都是有更新的，关键是plt.figure的set_data和set_offsets只在第一次触发，第二次及以后未能正常绘制原来的axex部分

**Comment by zhaohaojie1998** [comment]
动作空间是-1~1，你给个2是什么意思，肯定是加速度太大了，第二个时间步就撞墙了啊，导致回合重置了啊

**Comment by Horseant** [comment]
调整了动作空间之后还是存在这个问题，只绘制了一张图，后续的没有在这张图上面更新，包括那几个训练和测试的demo，数据是有更新的，但是就是那个绘制的方法plt.figure的set_data和set_offsets没有生效

**Comment by zhaohaojie1998** [comment]
可能是你的mpl有点问题，我几台设备上运行都没问题
