### ISSUE TITLE
大佬，训练效果太差如何解决呢

### ISSUE THREAD

**Issue by Chen1DONG** [zhaohaojie1998/DRL-for-Path-Planning#7]
大佬你好，我在运行demo_train_mixed_obs.py这个文件时，训练到了3万次，无人机依旧找不到合适的路径，还是在乱撞，想问下如何解决，需要调参吗

![微信截图_20240527181341](https://github.com/zhaohaojie1998/DRL-for-Path-Planning/assets/167983177/7d64b87c-0f80-4ffc-8126-c303f460a717)

![out33750](https://github.com/zhaohaojie1998/DRL-for-Path-Planning/assets/167983177/eb42b193-974a-41b7-b484-3b6712883d15)

![out33700](https://github.com/zhaohaojie1998/DRL-for-Path-Planning/assets/167983177/52885bc8-7bfb-4d18-901d-ed09e311d93b)

**Comment by zhaohaojie1998** [comment]
肯定得调啊，奖励函数超参数等都得自己设计啊。
代码的核心是SAC算法部分，只是提供了一个SAC算法的使用说明demo，环境只是随手搭的用于演示SAC算法的使用。

**Comment by zhaohaojie1998** [comment]
在环境里，可以找一下避障的参考文献，按他们的思路设计
