### ISSUE TITLE
训练后期还会碰撞

### ISSUE THREAD

**Issue by ThreeHu** [zhaohaojie1998/DRL-for-Path-Planning#8]
大佬你好，想问一下这个训练后期，奖励拉高之后还是会有好多碰撞情况是正常的吗，因为看到你贴出的奖励图后期也有很多低奖励情况，看数值应该也是碰撞产生的，这是什么原因，是SAC的探索吗？还有训练足够多的次数后把模型拿出来测试跑，换地图，成功率也不是很高，这个原因大概是出在哪里。

**Comment by zhaohaojie1998** [comment]
这取决于你的奖励函数、观测空间、雷达性能、训练方法、地图等多方面设计，环境代码就只是提供一个环境搭建demo，需要根据需求自己修改

**Comment by ThreeHu** [comment]
好的好的，请问一下您提供的这个奖励函数在训练后期还会有很高的碰撞概率嘛

**Comment by ThreeHu** [comment]
好的好的大佬，请问一下您这个奖励趋势图后面的波动主要是出现在什么情况，在什么情况下出现的负值奖励呀？是碰撞情况还是探索情况，谢谢大佬

**Comment by zhaohaojie1998** [comment]
应该和环境设计有关，环境就是瞎写的测试算法用的
